# Generated by Django 4.0.1 on 2022-01-09 00:24

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mobile_no', models.CharField(blank=True, help_text='10 Digit Mobile Number', max_length=10, null=True, unique=True, validators=[user_app.models.validate_mobile_no])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
